apiVersion: apps/v1
kind: Deployment
metadata:
   name: sampleapp-demo
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         sampleapp: web
   template:
      metadata:
         labels:
            sampleapp: web
      spec:
         containers:
            - name: sampleapp-site
              image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/sampleapp:latest
              imagePullPolicy: Always
              
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp-entrypoint
spec:
  selector:
    app: sampleapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Match the container port
  type: LoadBalancer # Use 'LoadBalancer' if you want an external IP
