apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
        - name: sampleapp-container
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/sampleapp:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flutter-LB
spec:
  selector:
    app: sampleapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # Match the container port
  type: LoadBalancer # Use 'LoadBalancer' if you want an external IP
